AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false
