AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false
